version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: users
    volumes:
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

  app:
    build: .
    # command: tail -f /dev/null
    # entrypoint: ""
    restart: always
    ports:
      - "8000:8000"
    environment:
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongo:27017/users
    volumes:
      - ./:/usr/src/app
